- hosts: members
  tasks:
    - ansible.windows.win_dns_client:
        adapter_names: '*'
        dns_servers: "{{ PDC_IP_ADDR }}"

    - microsoft.ad.membership:
        dns_domain_name: "{{ DOMAIN_NAME }}"
        domain_admin_user: "Administrator@{{ DOMAIN_NAME }}"
        domain_admin_password: "{{ lookup('ansible.builtin.env', 'DEFAULT_DA_USER_PASSWORD') }}"
        state: domain
      register: domain_join

    - ansible.windows.win_reboot:
        post_reboot_delay: 600
      when: domain_join.reboot_required
